version: "3.0"

services:
  frontend:
    image: "nginx"
    ports:
     - 80:80
    volumes:
     - ./engine:/app
     - ./assets/site.conf:/etc/nginx/conf.d/site.conf
    networks:
     - frontend
     - backend
  core:
    image: "arkhotech/php-fpm:7.2"
    volumes:
      - ./engine:/app
    networks:
      - backend

  database:
    image: "mysql:5.7.22"
    networks:
      - backend
    volumes:
      - data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "aloja123"
      MYSQL_DATABASE: "engine"
      MYSQL_USER: "workflow"
      MYSQL_PASSWORD: "workflow123"

networks:
  backend:
    driver: bridge
  frontend: 
    driver: bridge

volumes:
  data:
    
